# Generated by Django 4.0.2 on 2022-02-27 20:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilenumber', '0002_phonemodel_status_alter_phonemodel_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500)),
                ('date_posted', models.DateTimeField(default=datetime.datetime(2022, 2, 28, 1, 6, 5, 234373))),
                ('reviewnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilenumber.phonemodel')),
            ],
        ),
    ]
