# Generated by Django 4.0.2 on 2022-02-27 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilenumber', '0003_reviewmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='date_reported',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 1, 7, 53, 702510)),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 1, 7, 53, 844780)),
        ),
    ]
