# Generated by Django 4.0.2 on 2022-02-27 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilenumber', '0004_phonemodel_date_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='review_status',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='date_reported',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 1, 59, 21, 4682)),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 1, 59, 21, 135702)),
        ),
    ]
