# Generated by Django 4.0.2 on 2022-02-27 23:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilenumber', '0005_reviewmodel_review_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonemodel',
            name='date_reported',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 4, 13, 32, 902619)),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='reviewmodel',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 28, 4, 13, 33, 20845)),
        ),
    ]
